[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.120.4",
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "pydantic>=2.12.3",
    "uvicorn>=0.38.0",
]
